image: 
  repository: princep260471/complete-devops-project
  tag: 004f6a1
  pullPolicy: IfNotPresent
service: 
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
httpRoute:
  enabled: false